# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - embedding: OpenAI
  - text_splitter: RecursiveCharacter
  - llm: ChatOpenAI

_target_: llmflowoptimizer.component.model.sample_qa.SampleQA # what we defined on llmflowoptimizer/models/sample_qa.py

data_path: ${paths.reference_data_dir}/nyc_wikipedia.txt
