_target_: llmflowoptimizer.models.sample_qa.SampleQA # what we defined on llmflowoptimizer/models/sample_qa.py

data_path: ${paths.reference_data_dir}/nyc_wikipedia.txt

embedding:
  _target_: langchain.embeddings.OpenAIEmbeddings

text_splitter:
  _target_: langchain.text_splitter.RecursiveCharacterTextSplitter
  chunk_size: 500
  chunk_overlap: 50


llm_for_answer:
  _target_: langchain.chat_models.ChatOpenAI
  model_name: gpt-3.5-turbo
  temperature: 0