# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - paths: default
  - model: default
  - evaluation: default
  - extras: default
  - hydra: default

  - experiment: null
  - hparams_search: null

# task name, determines output directory path
task_name: "initial_task"
