# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - paths: default
  - model: sample
  - evaluation: default
  - extras: default

  - experiment: null

# task name, determines output directory path
task_name: "train"
